version: '3.7'
services:
  fraqbot:
    container_name: fraqbot
    restart: always
    image: drewpearce/trd-fraqbot
    # build: fraqbot/
    env_file: .env
    volumes:
      - '$HOME/logs:/tmp/logs'
      - ./fraqbot/Local/coins_tx:/usr/src/app/Local/coins_tx
    networks:
      legobot:
        aliases:
          - legobot

networks:
  legobot:
    name: legobot
    external: false
