connectors:
  Slack:
    enabled: true
    path: Legobot.Connectors.Slack.Slack
    kwargs:
      token: <a Slack API token>
helpEnabled: true
legos:
  Shakespeare:
    enabled: true
    path: Local.shakespeare.Shakespeare # Import path to the Lego Class
    kwargs:
      acl: # acl restricts Lego interaction to only whitelist/blacklist. Usefor for testing.
        whitelist:
          - <a Slack user ID>
      name: ShakespeareQuotes
      admins:
        - <a Slack user ID>
      triggers:
        - "!shake"
      pool_excludes:
        - <a Slack bot ID> # Keeps fraqbot from getting paid from the pool.
  