connectors:
  Slack:
    enabled: true
    path: Legobot.Connectors.Slack.Slack
    kwargs:
      token: ${{ENV::SLACK_TOKEN}}
helpEnabled: true
legos:
  APOD:
    enabled: true
    path: legos.apod.APOD
    kwargs:
      key: ${{ENV::APOD_KEY}}
  AshokCoin:
    enabled: true
    path: Local.coins.Coins
    kwargs:
      name: AshokCoin
      starting_value: 200
      triggers:
        - '!ashokcoin'
        - '!ak'
      defaults:
        admins: ${{LIST::ENV::ADMINS}}
        pool_excludes:
          - ${{ENV::FRAQBOT_ID}}
        secret_word_channels:
          - general
          - random
        disbursement_channels:
          - general
      # seeds:
      #   transaction:
      #     file: ${tx_dir}/tx.csv
      #     load_kwargs:
      #       f_type: csv
      #       delimiter: '|'
      #     transform: '[].{tx_timestamp: to_number(Timestamp), payer_id: Payer, payee_id: Payee, amount: to_number(Amount), memo: string_or_null(Memo)}'
      #   balance:
      #     file: ${tx_dir}/balances.json
      #     transform: key_val_to_fields(@, 'user', 'balance')
  AshokCoinAdmin:
    enabled: true
    path: Local.coins.CoinsAdmin
    kwargs:
      name: AshokCoin
      triggers:
        - '!ashokcoin'
        - '!ak'
      defaults:
        admins: ${{LIST::ENV::ADMINS}}
        pool_excludes:
          - ${{ENV::FRAQBOT_ID}}
        secret_word_channels:
          - general
          - random
        disbursement_channels:
          - general
  AshokCoinSecretWord:
    enabled: true
    path: Local.coins.CoinsSecretWord
    kwargs:
      name: AshokCoin
      defaults:
        admins: ${{LIST::ENV::ADMINS}}
        pool_excludes:
          - ${{ENV::FRAQBOT_ID}}
        secret_word_channels:
          - general
          - random
  AshokCoinMiner:
    enabled: true
    path: Local.coins.CoinsMiner
    kwargs:
      name: AshokCoin
      defaults:
        admins: ${{LIST::ENV::ADMINS}}
        pool_excludes:
          - ${{ENV::FRAQBOT_ID}}
        disbursement_channels:
          - general
      acl:
        blacklist: ${{LIST::ENV::MINER_BLACKLIST}}
  AshokCoinPool:
    enabled: true
    path: Local.coins.CoinsPoolManager
    kwargs:
      name: AshokCoin
      triggers:
        - '!ashokcoin'
        - '!ak'
      defaults:
        admins: ${{LIST::ENV::ADMINS}}
        pool_excludes:
          - ${{ENV::FRAQBOT_ID}}
        secret_word_channels:
          - general
          - random
        disbursement_channels:
          - general
      properties:
        - name: common_words
          file:
            path: data/lists/common_words.txt
            raw: true
            split_lines: true
            default: []
  Bible:
    enabled: false
    path: Local.bible.Bible
  FactSphere:
    enabled: true
    path: legos.fact_sphere.FactSphere
  Crypto:
    enabled: true
    path: legos.stocks.Cryptocurrency
  Memes:
    enabled: true
    path: legos.memes.Memes
    kwargs:
      font: impact
      config:
        templates:
          hjw:
            name: High James White
            custom: ${{ENV::BUCKET}}/memes/hjw.jpg
          zoidberg:
            name: Why Not Zoidberg?
            custom: ${{ENV::BUCKET}}/memes/zoidberg.jpg
          hey:
            name: Ron Burgundy Hey Everyone
            custom: https://i.ytimg.com/vi/vk7NcXWK7BQ/maxresdefault.jpg
          puff:
            name: Fraq Take a Puff
            custom: ${{ENV::BUCKET}}/memes/puff.png
          ua:
            name: Unamused Ashok
            custom: ${{ENV::BUCKET}}/memes/unamused.jpg
          pgm:
            name: Pro Gamer Move
            custom: https://i.kym-cdn.com/photos/images/newsfeed/001/498/705/803.png
          hacker:
            name: Mr. Robot Hacker
            custom: https://i.imgflip.com/21ghhf.jpg
          dat:
            name: Dat ___
            custom: https://i.kym-cdn.com/photos/images/original/000/578/079/477.jpg
          evil:
            name: Dr. Evil Scare Quotes
            custom: https://i.imgflip.com/4/siw7k.jpg
          dinkleberg:
            name: Dinkleberg
            custom: https://i.imgflip.com/ukx.jpg
  Moin:
    enabled: true
    path: Local.moin.Moin
    kwargs:
      url_base: ${{ENV::BUCKET}}/moin/
      api_base: http://moins:5000/moins
      moin_channels:
        - general
        - random
      rate_config:
        rate_key: metadata.source_user
        rate_interval: 14400
  NewJob:
    enabled: true
    path: Local.newjob.NewJob
    kwargs:
      properties:
        - name: role_modifiers_list
          file:
            path: 'data/lists/role_modifiers.txt'
            raw: true
            split_lines: true
            default: []
        - name: roles_list
          file:
            path: 'data/lists/roles.txt'
            raw: true
            split_lines: true
            default: []
        - name: companies_list
          file:
            path: 'data/lists/companies.txt'
            raw: true
            split_lines: true
            default: []
  RandomEmoji:
    enabled: true
    path: Local.randomemoji.RandomEmoji
    kwargs:
      properties:
        - name: default_emojis
          file:
            path: 'data/lists/default_emojis.json'
            default: []
  Shakespeare:
    enabled: true
    path: Local.shakespeare.Shakespeare
    kwargs:
      properties:
        - name: insult_array
          file:
            path: 'data/lists/quotes.txt'
            raw: true
            split_lines: true
            default: []
  XKCD:
    enabled: true
    path: Local.xkcd.XKCD
  XMasPlot:
    enabled: true
    path: Local.xmasplot.XMasPlot
    kwargs:
      api: ${{ENV::FRAQ_QUOTES}}/plots/christmas
  YourFace:
    enabled: true
    path: Local.yourface.YourFace
    kwargs:
      token: ${{ENV::SLACK_TOKEN}}
      api: ${{ENV::FRAQ_QUOTES}}/trd/pikachu
      url_base: ${{ENV::BUCKET}}/cheats/
log_file: /tmp/logs/fraqbot.log
log_level: DEBUG
